<?php if ($this->pageCount): ?>
<ul class="pagination">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
    <li><a class="previous" href="<?php echo $this->url().'?page='.$this->previous; ?>">Previous</a><li>
<?php else: ?>
    <li><span class="previous">Previous</span></li>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li><a href="<?php echo $this->url().'?page='.$page; ?>"><?php echo $page ?></a></li>
  <?php else: ?>
    <li><a class="selected" href="<?php echo $this->url().'?page='.$page; ?>"><?php echo $page ?></a></li>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
    <li><a class="previous" href="<?php echo $this->url().'?page='.$this->next; ?>">Next</a><li>
<?php else: ?>
    <li><span class="previous">Next</span></li>
<?php endif; ?>
</ul>
<?php endif; ?>

