<?php
namespace Asset\Model;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Extension.
 * Generated by PHPUnit on 2010-02-23 at 11:51:12.
 */
class ExtensionTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var Extension
     */
    protected $extension;

    protected $type;
    protected $mimeType;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->extension = new Extension('jpg');
        $this->type = new Type('image', 'Image');
        $this->mimeType = new MimeType('image/jpg', $this->type);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    public function test__constructor() {
        $this->assertEquals('jpg', $this->extension->getSysname());
    }

    public function testSetMimeType() {
        $this->extension->setMimeType($this->mimeType);
        $this->assertEquals($this->mimeType, $this->extension->getMimeType());
    }
}
?>
