<?php
namespace Asset\Model;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Group.
 * Generated by PHPUnit on 2010-02-23 at 11:51:12.
 */
class GroupTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var Group
     */
    protected $group;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->group = new Group('default', 'Default');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    public function test__constructor() {
        $this->assertEquals('default', $this->group->getSysname());
        $this->assertEquals('Default', $this->group->getTitle());
    }
    /**
     * @todo Implement testAddSize().
     */
    public function testAddSize() {
        $size = new Size(100, 200);
        $this->group->addSize('100x200', $size);
        $this->assertEquals('100x200', $size->getSysname());
        $this->assertEquals('100x200', $size->getTitle());
        $this->assertEquals($this->group, $size->getGroup());
        $this->assertEquals(1, count($this->group->sizes));

        $size = new Size(200, 100);
        $this->group->addSize('200x100', $size);
        $this->assertEquals('200x100', $size->getSysname());
        $this->assertEquals('200x100', $size->getTitle());
        $this->assertEquals($this->group, $size->getGroup());
        $this->assertEquals(2, count($this->group->sizes));
    }

    public function testGetLocation()
    {
        $expected = APPLICATION_ROOT . '/data/assets/default';
        $this->assertEquals($expected, $this->group->getLocation());
    }
}
?>
