<?php
namespace Asset\Model;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for MimeType.
 * Generated by PHPUnit on 2010-02-23 at 11:51:11.
 */
class MimeTypeTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var MimeType
     */
    protected $mimeType;
    protected $type;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->type = new Type('image', 'Image');
        $this->mimeType = new MimeType('image/jpg', $this->type);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    public function test__constructor() {
        $this->assertEquals('image/jpg', $this->mimeType->getSysname());
        $this->assertEquals($this->type, $this->mimeType->getType());
        $this->assertEquals(0, count($this->mimeType->extensions));
    }

    public function testAddExtension() {
        $ext = new Extension('jpg');
        $this->mimeType->addExtension($ext);
        $this->assertEquals(1, count($this->mimeType->extensions));
    }

    public function testAddExtensions() {
        $exts = array(
            new Extension('jpg'),
            new Extension('png')
        );
        $this->mimeType->addExtensions($exts);
        $this->assertEquals(2, count($this->mimeType->extensions));
    }

    public function testIsValidExtension() {
        $exts = array(
            new Extension('jpg'),
            new Extension('png')
        );
        $this->mimeType->addExtensions($exts);
        $this->assertTrue($this->mimeType->isValidExtension('jpg'));
        $this->assertFalse($this->mimeType->isValidExtension('jpeg'));
    }
}
?>
