<?php
namespace Asset\Model;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Size.
 * Generated by PHPUnit on 2010-02-23 at 11:51:12.
 */
class SizeTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var Size
     */
    protected $size;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->size = new Size(100, 200);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    public function test__constructor() {
        $this->assertEquals(100, $this->size->width);
        $this->assertEquals(200, $this->size->height);
    }

    public function testSetCrop() {
        $this->size->setCrop(true);
        $this->assertTrue($this->size->getCrop());
    }

    public function testGetTitle() {
        $this->assertNull($this->size->getTitle());

        $this->size->setTitle('testTitle');
        $this->assertEquals('testTitle', $this->size->getTitle());
    }
}
?>
