<?php
namespace Asset\Model;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Type.
 * Generated by PHPUnit on 2010-02-23 at 11:51:11.
 */
class TypeTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var Type
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Type('image', 'Image');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    public function test__constructor() {
        $this->assertEquals('image', $this->object->getSysname());
        $this->assertEquals('Image', $this->object->getTitle());
    }
}
?>
