<?php echo $this->render('partials/header.phtml'); ?>

    <div id="wrapper" class="one-column">


        <div id="header">
            <h1><a href="/" class="page-title">CMS</a></h1>

            <ul id="menu">
                <li><a href="/">Home</a></li>
                <li><a href="/blog/add">Blog Admin</a></li>
            </ul><!-- menu -->
        </div>

        <div id="main">
            <?php echo $this->layout()->main ?>
        </div><!-- page -->
    </div><!-- wrapper -->

<?php echo $this->render('partials/footer.phtml'); ?>