<?php
namespace Core\Model;

require_once 'PHPUnit/Framework.php';
//require_once '../../../bootstrap.php';

/**
 * Test class for Entity.
 * Generated by PHPUnit on 2009-12-16 at 10:46:52.
 */
class AbstractModelTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var Entity
     */
    protected $model;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->model = new \Mock\Model;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    public function testBadGet ()
    {
        $this->setExpectedException('\Exception');
        $this->model->badProperty;
    }

    public function test__getAnd__set() {
        $this->model->num = 1;
        $this->assertEquals($this->model->num, 1);
        $this->assertFalse($this->model->hit);

        $this->model->setNum(2);
        $this->assertEquals($this->model->num, 2);
        $this->assertEquals($this->model->getNum(), 2);
    }

    public function test__getAnd__setCallFunctionsFirst() {
        $this->model->name = 'test';
        $this->assertTrue($this->model->hit);

        $this->model->hit = false;
        $this->model->name;
        $this->assertTrue($this->model->hit);
    }

    public function test__call() {
        $this->model->testHit();
        $this->assertTrue($this->model->hit);
    }

    public function test__callBad() {
        $this->setExpectedException('\Exception');
        $this->model->badFunctionCall();
    }

    public function testSetData() {
        $array = array('num' => 1, 'name' => 'test', 'fake' => 'cool');
        $this->model->setData($array);
        $this->assertEquals($this->model->num, 1);
        $this->assertEquals($this->model->name, 'test');
    }

    public function testIsset()
    {
        $this->assertTrue(isset($this->model->name));
        $this->assertFalse(isset($this->model->random));
    }

    public function testGetIdentifier()
    {
        $this->assertEquals($this->model->getIdentifier(), $this->model->getId());
    }

    public function testSetId()
    {
        $this->setExpectedException('\Core\Model\Exception');
        $this->model->setId(2);
    }

    public function testGetCollectionAsArray()
    {
        $collection = array(
            new TestObject(),
            new TestObject()
        );

        $data = array(
            array(
                'one' => 1,
                'two' => 2
            ),
            array(
                'one' => 1,
                'two' => 2
            )
        );

        $model = new ConcreteAbstractModel();
        $newData = $model->getCollectionAsArray($collection);
        $this->assertEquals($data, $newData);

        $data = array(
            array(
                'one' => 1,
                'two' => 2,
                'three' => 3
            ),
            array(
                'one' => 1,
                'two' => 2,
                'three' => 3
            )
        );
        $newData = $model->getCollectionAsArray($collection, array('options' => array()));
        $this->assertEquals($data, $newData);

    }
}


class ConcreteAbstractModel extends AbstractModel
{
    public function getCollectionAsArray($collection, $options = null)
    {
        return  parent::_getCollectionAsArray($collection, $options);
    }
}

class TestObject
{
    public function toArray($includes)
    {
        $data = array('one' => 1, 'two' => 2);
        
        if(isset($includes['options'])) {
            $data['three'] = 3;
        }

        return $data;
    }
}