<?php
namespace Core\Model;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Content.
 * Generated by PHPUnit on 2010-01-20 at 16:07:51.
 */
class ContentTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Content
     */
    protected $content;

    protected $page;
    protected $pageRoute;


    protected function setUp()
    {
        $this->content = new \Mock\Content;

        $layout = new \Core\Model\Layout('test');
        $this->page = new \Core\Model\Page($layout);
        $route = new \Core\Model\Route('route');
        $this->pageRoute = $route->routeTo($this->page);
    }

    protected function tearDown()
    {
    }

    public function testGetURL()
    {
        $this->assertNull($this->content->getURL());
    }

    public function testSetDependentPage()
    {
        $this->content->setDependentPage($this->page);
        $this->assertEquals($this->page, $this->content->getDependentPage());
    }

    public function testSetDependentPageGivesPagePrimaryURL()
    {
        $this->content->setDependentPage($this->page);
        $this->assertEquals($this->pageRoute->getURL(), $this->content->getURL());
        $this->assertEquals('/route/', $this->content->getURL());
    }

    public function testGetResourceId()
    {
        $this->assertEquals('Content.' . $this->content->id, $this->content->getResourceId());
    }

    public function testRoles()
    {
        $acl = new \Zend_Acl();
        $acl->addRole('admin');
        $acl->addRole('user');
        $acl->addResource(new \Zend_Acl_Resource('Content.'));
        $acl->allow('admin', null, array('view', 'add', 'edit', 'delete'));
        \Zend_Registry::set('acl', $acl);

        $this->assertEquals(TRUE, $this->content->canView('admin'));
        $this->assertEquals(TRUE, $this->content->canAdd('admin'));
        $this->assertEquals(TRUE, $this->content->canEdit('admin'));
        $this->assertEquals(TRUE, $this->content->canDelete('admin'));

        $this->assertEquals(FALSE, $this->content->canView('user'));
        $this->assertEquals(FALSE, $this->content->canAdd('user'));
        $this->assertEquals(FALSE, $this->content->canEdit('user'));
        $this->assertEquals(FALSE, $this->content->canDelete('user'));
    }
}
?>
