<?php
namespace Core\Model;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Content.
 * Generated by PHPUnit on 2010-01-20 at 16:07:51.
 */
class ContentTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Content
     */
    protected $content;

    protected $page;
    protected $pageRoute;


    protected function setUp()
    {
        $this->content = new \Mock\Content;

        $layout = new \Core\Model\Layout('test');
        $this->page = new \Core\Model\Page($layout);
        $route = new \Core\Model\Route('route');
        $this->pageRoute = $route->routeTo($this->page);
    }

    protected function tearDown()
    {
    }

    public function testGetURL()
    {
        $this->assertNull($this->content->getURL());
    }

    public function testSetDependentPage()
    {
        $this->content->setDependentPage($this->page);
        $this->assertEquals($this->page, $this->content->getDependentPage());
    }

    public function testSetDependentPageGivesPagePrimaryURL()
    {
        $this->content->setDependentPage($this->page);
        $this->assertEquals($this->pageRoute->getURL(), $this->content->getURL());
        $this->assertEquals('/route/', $this->content->getURL());
    }
}
?>
