<?php
namespace Core\Model;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Template.
 * Generated by PHPUnit on 2010-01-28 at 11:30:39.
 */
class TemplateTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Template
     */
    protected $template;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->template = new Template('test', new \Core\Model\Layout('test'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testConstructor()
    {
        $template = new Template('Test', new \Core\Model\Layout('test'));
        $this->assertEquals('Test', $template->getSysname());
    }

    public function testSetSysname()
    {
        $this->template->setSysname('Test');
        $this->assertEquals('Test', $this->template->getSysname());
    }

    public function testSetSysnameNull()
    {
        $this->setExpectedException('Core\Model\Exception');
        $this->template->setSysname(null);
    }

    public function testSetSysnameShort()
    {
        $this->setExpectedException('Core\Model\Exception');
        $this->template->setSysname('12');
    }

    public function testSetSysnameLong()
    {
        $this->setExpectedException('Core\Model\Exception');
        //51 chars
        $this->template->setSysname('2w953y7886j7bubqe9d809b4qoksfgn8vl57bz1coml32pr79l1');
    }
}
?>
