<?php
namespace Core\Model\Module;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for View.
 * Generated by PHPUnit on 2009-12-28 at 15:28:19.
 */
class ViewTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var View
     */
    protected $view;

    protected $module;

    protected $resource;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->module = new \Core\Model\Module('Core', 'Core');
        $this->resource = new ContentType('Test', 'test', 'Mock\Block\Dynamic\Form\NonAbstractForm');
        $this->module->addResource($this->resource);
        $this->view = new View($this->resource, 'test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testMapViewScriptCore()
    {
        $this->view->resource->module->sysname = 'Core';
        $this->view->resource->discriminator = 'Text';
        $this->view->sysname = 'default';

        $this->assertEquals(APPLICATION_PATH.'/Core/View/', $this->view->getBasePath());
        $this->assertEquals('Content/Text/default.phtml', $this->view->getFile());
    }

    public function testMapViewScriptModule()
    {
        $this->view->resource->module->sysname = 'Blog';
        $this->view->resource->discriminator = 'Article';
        $this->view->sysname = 'article';

        $this->assertEquals(APPLICATION_PATH.'/Blog/View/', $this->view->getBasePath());
        $this->assertEquals('Content/Article/article.phtml', $this->view->getFile());
    }

    public function testConstructor()
    {
        $view = new View($this->resource, 'Text');
        $this->assertEquals($this->resource, $view->getResource());
        $this->assertEquals('Text', $view->sysname);
    }

    public function testRender()
    {
        $this->view->resource->module->sysname = 'Core';
        $this->view->resource->discriminator = 'Text';
        $this->view->sysname = 'default';
        
        $this->view->getInstance()->render($this->view->getFile());

        $this->view->getInstance()->render('Content/Text/default.phtml');
    }

    public function testGetInstance()
    {
        $helperLoader = new \Zend_Loader_PluginLoader();
        \Core\Model\Module\View::setPluginLoader($helperLoader, 'helper');

        $filterLoader = new \Zend_Loader_PluginLoader();
        \Core\Model\Module\View::setPluginLoader($filterLoader, 'filter');
    }
}
?>
