<?php
namespace User\Model;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Group.
 * Generated by PHPUnit on 2010-03-31 at 09:52:29.
 */
class GroupTest extends \User\UserModuleTestCase {

    public function test__construct() {
        $this->assertEquals('Test', $this->testGroup->getName());
    }

    public function testAddRole() {
        $this->assertContains($this->groupRole, $this->testGroup->getRoles());
    }

    public function testRemoveRole() {
        $this->assertContains($this->groupRole, $this->testGroup->getRoles());
        $this->testGroup->removeRole($this->groupRole);
        $this->assertNotContains($this->groupRole, $this->testGroup->getRoles());
    }
}
?>