<?php
namespace User\Model;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Identity.
 * Generated by PHPUnit on 2010-03-31 at 09:52:30.
 */
class IdentityTest extends \User\UserModuleTestCase {
    /**
     * @var Identity
     */
    protected $identity;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        parent::setUp();
        $this->identity = new Identity('local', 'test', $this->user);
    }

    public function test__construct()
    {
        $this->assertEquals('local', $this->identity->getType());
        $this->assertEquals('test', $this->identity->getIdentity());
        $this->assertEquals($this->user, $this->identity->getUser());
    }

    public function testSetIdentity() {
        $this->setExpectedException('Modo\Model\Exception');
        $this->identity->setIdentity('');
    }

    public function testSetType() {
        $this->setExpectedException('Modo\Model\Exception');
        $this->identity->setType('');
    }

    public function testSetPassHash() {
        $this->identity->setPassHash('ssfdfsafsaf');
        $this->assertEquals('ssfdfsafsaf', $this->identity->getPassHash());
    }

    public function testSetPassHashFailsOnEmpty() {
        $this->setExpectedException('Modo\Model\Exception');
        $this->identity->setPassHash('');
    }

    public function testSetUser() {
        $this->setExpectedException('\Exception');
        $this->session->setUser(null);
    }
}
?>
