<?php
namespace User\Model;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Session.
 * Generated by PHPUnit on 2010-03-31 at 09:52:30.
 */
class SessionTest extends \User\UserModuleTestCase {

    public function test__construct() {
        $this->assertEquals($this->user, $this->session->getUser());
        $this->assertEquals(new \DateTime(), $this->session->getDateStarted());
        $this->assertEquals(new \DateTime(), $this->session->getDateActive());
        $this->assertEquals('127.0.0.1', $this->session->getIpAddress());
        $this->assertEquals('test', $this->session->getUserAgent());
    }

    public function testSetUser() {
        $this->setExpectedException('\Exception');
        $this->session->setUser(null);
    }

    public function testSetDateStarted() {
        $this->session->setDateStarted();
        $this->assertEquals(new \Datetime(), $this->session->getDateStarted());
    }

    public function testSetDateActive() {
        $this->session->setDateActive();
        $this->assertEquals(new \Datetime(), $this->session->getDateActive());
    }
}
?>
