<?php
namespace Core\Model\Layout;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Location.
 * Generated by PHPUnit on 2010-01-28 at 15:17:22.
 */
class LocationTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Location
     */
    protected $location;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->location = new Location('test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testSetSysname()
    {
        $this->location->setSysname('test2');
        $this->assertEquals('test2', $this->location->getSysname());
    }

    public function testSetSynameNull()
    {
        $this->setExpectedException('Core\Model\Exception');
        $this->location->setSysname(null);
    }

    public function testAddContent()
    {
        $this->location->addContent('here');
        $this->location->addContent(' is more content');
        $this->assertEquals('here is more content', $this->location->content);
    }

    public function testGetIdentifier()
    {
        $this->assertEquals($this->location->getSysname(), $this->location->getIdentifier());
    }
}
?>
