<div id="actionbar">
<ul class="primary">
    <li class="dropdown">
        <a href="#" class="top dropdown"><span class="actionbar-site">Site</span></a>
        <ul class="first" style="display: none;">
            <li class="first">
                <a href="/index/text" class="page-block-index">Shared Blocks</a>
            </li>
            <li class="last">
                <a href="/logout" class="logout">Logout</a>
            </li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" class="top dropdown"><span class="actionbar-page">Page</span></a>
        <ul class="first" style="display: none;">
            <li class="dropdown first">
                <span class="actionbar-new dropdown">New</span>
                <ul style="display: none;">
                    <li class="first">
                        <a href="#" class="addPage">Page</a>
                    </li>
                    <li class="last">
                        <a href="#/direct/content/add/?type=Text&isShared=true" class="sharedBlock-add">Shared Block</a>
                    </li>
                </ul>
            </li>
            <li><a class="editPage" href="#">Edit</a></li>
            <li class="last"><a class="deletePage" href="#">Delete</a></li>
        </ul>
    </li>
</ul>
<ul class="icons">
    <li id="editToggle" class="edit">
        <a href="#">Edit</a>
    </li>
</ul>
</div>