<!doctype html>
<html>
<head>

	<meta charset="utf-8" />
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<meta name="author" content="Modo Design Group" />
	<meta name="keywords" content="" />
	<meta name="description" content="<?php echo $this->layout()->page->getDescription(); ?>" />

	<title>CMS<?php if ($this->layout()->page->getTitle()) echo ' :: ' . $this->layout()->page->getTitle(); ?></title>

	<!--[if IE]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<style>
	  article, aside, details, figcaption, figure, footer, header,
	  hgroup, menu, nav, section { display: block; }
	</style>

<?php
    $this->headLink()->appendStylesheet('/resources/vendor/js/jquery-ui/themes/base/jquery-ui.css');
    $this->headLink()->appendStylesheet('/resources/core/css/base.css');
    $this->headLink()->appendStylesheet('/resources/core/css/theme.css');
    $this->headLink()->appendStylesheet('/resources/core/css/page.css');

    $this->headScript()->appendFile('/resources/vendor/js/jquery.tmpl.min.js');


    if (\Core\Auth\Auth::getInstance()->getIdentity()->isAllowed('AdminMenu', 'view')) {
        $this->headScript()->appendFile('/resources/core/js/CMS.js');
        $this->headLink()->appendStylesheet('/resources/core/css/admin.css');
        $this->headScript()->appendFile('/resources/vendor/js/ckeditor/ckeditor.js');
        $this->headScript()->appendFile('/resources/vendor/js/ckeditor/adapters/jquery.js');
    }
    echo $this->headLink();
    echo $this->jQuery()
            ->enable()
            ->uiEnable()
            ->setVersion('1.4.3')
            ->setUiVersion('1.8.4')
            ->addJavascriptFile('/resources/taxonomy/js/jquery.formtag.js')
            ->addJavascriptFile('/resources/asset/js/jquery.formupload.js')
            ->addJavascriptFile('/resources/vendor/js/swfupload.js');
    echo $this->headScript();
?>

    <!--[if lt IE 8]>
	<link href="/resources/core/css/ie.css" rel="stylesheet" type="text/css" media="screen" />
    <![endif]-->

<?php if (\Core\Auth\Auth::getInstance()->getIdentity()->isAllowed('AdminMenu', 'view')) : ?>
    <script type="text/javascript">
    $(document).ready(function () {
        var Page;
        CMS.Use(['Core/CMS.Page', 'Core/CMS.AdminMenu'], function (CMS) {
            var AdminMenu = new CMS.AdminMenu();
        });
    });
    </script>
<?php endif; ?>

</head>

<?php if (isset($this->layout()->page)) : ?>
<body id="page-<?php echo $this->layout()->page->id; ?>">
    <?php if (\Core\Auth\Auth::getInstance()->getIdentity()->isAllowed('AdminMenu', 'view')) : ?>
        <?php echo $this->partial('partials/adminMenu.phtml', array('page' => $this->layout()->page)); ?>
    <?php endif; ?>
<?php else: ?>
<body>
<?php endif; ?>