<!doctype html>
<html>
<head>
	
	<meta charset="utf-8" />
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<meta name="author" content="Modo Design Group" />
	<meta name="keywords" content="" />
	<meta name="description" content="<?php echo $this->layout()->page->getDescription(); ?>" />

	<title>CMS<?php if ($this->layout()->page->getTitle()) echo ' :: ' . $this->layout()->page->getTitle(); ?></title>
	
	<!--[if IE]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<style>
	  article, aside, details, figcaption, figure, footer, header,
	  hgroup, menu, nav, section { display: block; }
	</style>
	<link href="/resources/core/js/jquery-ui/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" media="screen" />
	<link href="/resources/core/css/base.css" rel="stylesheet" type="text/css" media="screen" />
	<link href="/resources/core/css/theme.css" rel="stylesheet" type="text/css" media="screen" />
	<link href="/resources/core/css/page.css" rel="stylesheet" type="text/css" media="screen" />
<?php if (\Core\Auth\Auth::getInstance()->getIdentity()->isAllowed('AdminMenu', 'view')) : ?>
	<link href="/resources/core/css/admin.css" rel="stylesheet" type="text/css" media="screen" />
<?php endif; ?>
	<link href="/resources/core/js/jqModal/jqModal.css" rel="stylesheet" type="text/css" media="screen" />
    <!--[if lt IE 8]>
	<link href="/resources/core/css/ie.css" rel="stylesheet" type="text/css" media="screen" />
    <![endif]-->
    <script type="text/javascript" src="/resources/core/js/jquery.min.js"></script>
    <script type="text/javascript" src="/resources/core/js/jquery-ui/ui/minified/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/resources/core/js/jqModal/jqModal.js"></script>
    <script type="text/javascript" src="/resources/core/js/CMS/CMS.js"></script>

<?php if (\Core\Auth\Auth::getInstance()->getIdentity()->isAllowed('AdminMenu', 'view')) : ?>
    <script type="text/javascript" src="/resources/core/js/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
    CMS.Use(['Core/CMS.Page', 'Core/CMS.AdminMenu'], function (CMS) {
        this.Page = new CMS.Page(PAGE_INFO.data[0]);
        this.AdminMenu = new CMS.AdminMenu({page: this.Page});
    });
    </script>
<?php endif; ?>
</head>

<?php if (isset($this->layout()->page)) : ?>
<body id="page-<?php echo $this->layout()->page->id; ?>">
    <?php if (\Core\Auth\Auth::getInstance()->getIdentity()->isAllowed('AdminMenu', 'view')) : ?>
    <ul id="adminMenu">
        <li><a href="#" class="addPage">Add Page</a></li>
        <li><a href="#" class="editPage">Edit Page</a></li>
        <li><a href="#" class="deletePage">Delete Page</a></li>
        <?php //<li><a href="#" class="assetManager">Asset Manager</a></li> ?>
    </ul>
    <?php endif; ?>
<?php else: ?>
<body>
<?php endif; ?>