<?php
namespace User\Model\Identity;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Identity.
 * Generated by PHPUnit on 2010-03-31 at 09:52:30.
 */
class LocalTest extends \User\UserModuleTestCase {
    /**
     * @var Local
     */
    protected $identity;

    protected $_user;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        parent::setUp();
        $this->_user = \Mockery::mock('User\Model\User');
        $this->identity = new Local('test', 'testing', $this->_user);
    }

    public function test__construct()
    {
        $this->assertEquals('test', $this->identity->getIdentifier());
        $this->assertGreaterThan(59, strlen($this->identity->getPassHash()));
        $this->assertEquals($this->_user, $this->identity->getUser());
    }

    public function testSetIdentity() {
        $this->setExpectedException('Core\Model\Exception');
        $this->identity->setIdentifier('');
    }

    public function testSetPasswordFailsOnEmpty() {
        $this->setExpectedException('Core\Model\Exception');
        $this->identity->setPassword('');
    }

    public function testSetPassHashFailsOnEmpty() {
        $this->setExpectedException('Core\Model\Exception');
        $this->identity->setPassHash('');
    }

    public function testSetUser() {
        $this->setExpectedException('\Exception');
        $this->session->setUser(null);
    }
}
?>
