<?php
namespace Core\Model\Frontend;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Content.
 * Generated by PHPUnit on 2010-01-20 at 16:07:51.
 */
class ActionTest extends \PHPUnit_Framework_TestCase
{

    /**
     *
     * @var Action
     */
    public $action;

    protected function setUp()
    {
        $this->action = new Action('test');
    }

    protected function tearDown()
    {
    }

    public function testConstruct()
    {
    }
}

?>