<?php
namespace Core\Model\Frontend;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Content.
 * Generated by PHPUnit on 2010-01-20 at 16:07:51.
 */
class CodeTest extends \PHPUnit_Framework_TestCase
{

    /**
     *
     * @var Code
     */
    public $code;

    protected function setUp()
    {
        $this->code = new Code(1);
    }

    protected function tearDown()
    {
    }

    public function testConstruct()
    {
    }
}

?>