<li id="asset-${id}" class="asset">
    <div class="thumb">
        <img src="${thumb}" alt="${name}" />
    </div>
    <h3 class="name">${name}</h3>
    <p class="upload_date">${upload_date}</p>
    <div id="actions-${id}" class="actions">
        <ul>
        {{each(i, action) actions}}
            <li><a class="asset-action ${action}" href="#${action}-${id}">${action}</a></li>
        {{/each}}
        </ul>
        <div id="Insert-${id}" class="asset-insert">
            <form>
                <label for="size">Choose a size:</label>
                <select class='size' name="size">
                    {{each(i, size) sizes}}
                        <option value="${size.sysname}">${size.title}</option>
                    {{/each}}
                </select>

                <input type="submit" name="submit" class="insert" id="submit" value="Insert" class="button">
            </form>
        </div>
        <div id="Edit-${id}" class="asset-edit">
            <?php echo $this->editForm; ?>
        </div>
        <div id="Delete-${id}" class="asset-delete">
            <form action="/direct/asset/asset/delete?id=${id}&confirm=1">
                Are you sure you want to delete this image?<br/>
                <input class="submit" type="submit" value="Yes"/> <input class="cancel" type="submit" value="No"/>
            </form>
        </div>
    </div>
</li>