<?php
namespace User\Model\Acl;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Permission.
 * Generated by PHPUnit on 2010-03-31 at 09:52:47.
 */
class PermissionTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var Permission
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Permission('role', 'resource', 'privilege', true);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    public function test__construct() {
        $this->assertEquals('role', $this->object->getRole());
        $this->assertEquals('resource', $this->object->getResource());
        $this->assertEquals('privilege', $this->object->getPrivilege());
        $this->assertTrue($this->object->getAllow());
        $this->assertNull($this->object->getAssertion());
    }

    public function testSetRoleNull() {
        $this->object->setRole(null);
        $this->assertNull($this->object->getRole());
    }

    public function testSetResource() {
        $this->object->setResource(null);
        $this->assertNull($this->object->getResource());
    }

    public function testSetPrivilege() {
        $this->object->setPrivilege(null);
        $this->assertNull($this->object->getPrivilege());
    }

    public function testSetAllow() {
        $this->object->setAllow(false);
        $this->assertFalse($this->object->getAllow());

        $this->setExpectedException('Core\Model\Exception');
        $this->object->setAllow(null);
    }
    
    public function testSetAssertion() {
        $this->object->setAssertion('test');
        $this->assertEquals('test', $this->object->getAssertion());
    }
}
?>
