<?php
namespace User\Model\Acl;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Resource.
 * Generated by PHPUnit on 2010-03-31 at 09:52:47.
 */
class ResourceTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var Resource
     */
    protected $resource;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->resource = new Resource('test', 'testParent');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    public function test__construct() {
        $this->assertEquals('test', $this->resource->getSysname());
        $this->assertEquals('testParent', $this->resource->getParent());
    }

    public function testSetSysnameEmpty() {
        $this->setExpectedException('Modo\Model\Exception');
        $this->resource->setSysname('');
    }

    public function testSetParentNull() {
        $this->resource->setParent(null);
        $this->assertNull($this->resource->getParent());
    }

    public function testSetParentEmpty() {
        $this->setExpectedException('Modo\Model\Exception');
        $this->resource->setParent('');
    }

    public function testGetResourceId() {
        $this->assertEquals('test', $this->resource->getResourceId());
    }
}
?>
