<?php
namespace User\Model\Acl;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Role.
 * Generated by PHPUnit on 2010-03-31 at 09:52:46.
 */
class RoleTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var Role
     */
    protected $role;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->role = new Role('test', 'This is a test description');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    public function test__construct() {
        $this->assertEquals('test', $this->role->getSysname());
        $this->assertEquals('This is a test description', $this->role->getDescription());
    }

    public function testSetSysnameNull() {
        $this->setExpectedException('Modo\Model\Exception');
        $this->role->setSysname(null);
    }

    public function testGetRoleId() {
        $this->assertEquals('test', $this->role->getRoleId());
    }
}
?>
