<?php
namespace Core\Controller\Request;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Http.
 * Generated by PHPUnit on 2009-12-28 at 16:00:10.
 */
class HttpTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Http
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Http;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testSetRouteId()
    {
        $this->object->setRouteId(1);
        $this->assertEquals(1, $this->object->getRouteId());
    }

    public function testSetDirect()
    {
        $this->object->setDirect();
        $this->assertTrue($this->object->isDirect());
    }
}
?>
