<?php
namespace Core\Model\Content;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Text.
 * Generated by PHPUnit on 2010-01-28 at 16:34:48.
 */
class TextTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Text
     */
    protected $text;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->text = new Text('Test', 'This is a test.');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testConstructor()
    {
        $this->assertEquals('Test', $this->text->getTitle());
        $this->assertEquals('This is a test.', $this->text->getContent());
        $this->assertFalse($this->text->getShared());
    }

    public function testSetTitle()
    {
        $this->setExpectedException('Core\Model\Exception');

        $t = '';
        for($i = 0; $i < 11; $i++)
        {
            $t .= '0123456789';
        }
        $this->text->setTitle($t);
    }

    public function testSetContent()
    {
        $this->setExpectedException('Core\Model\Exception');

        $t = '';
        for($i = 0; $i < 6501; $i++)
        {
            $t .= '0123456789';
        }
        $this->text->setContent($t);
    }

    /**
     * @todo Implement testSetShared().
     */
    public function testSetShared()
    {
        $this->assertFalse($this->text->getShared());

        $this->text->setShared(true);
        $this->assertTrue($this->text->getShared());

        $this->setExpectedException('Core\Model\Exception');
        $this->text->setShared('test');
    }
}
?>
